### ISSUE TITLE
Add to list a companies, a company which you think is good to work for

### ISSUE THREAD

**Issue by draco-malfoy** [draco-malfoy/StartHub#1]
### Add a new company to already existing list of companies, by adding following details:

- website of company
- start year
- remote jobs (Yes/No)
- degree required(Yes/No)

### A friendly guide to create a pull request:
1. Star this repository (you must be logged on to your GitHub account, duh!)
2. Fork this repository
3. To add a company you need to modify the following files:
	- the main file _(List.md)_ (add a company in ascending alphabetic order)
	- company file ***(company_name.md)*** in the list directory
4. This can be done in either of the two ways:
	- **Method 1:** clone the repo locally on your PC
 	- **Method 2:** or make changes online on GitHub

#### Method 1:
This is the not-so beginner friendly way (or hard way, to say the least). But you got to do it if you really want to learn Git.
Follow [this](https://yangsu.github.io/pull-request-tutorial/) guide.

#### Method 2:
This is the easy-peasy way. You just:
* create a new file with the company's name(suffixed by _.md_) and all the following details
   * company website
   * company's career page
   * start year
   * remote work
   * no degree required
   * any other detail you find relevant
* modify the _List.md_ to add the company's name to the original list with few more details
 
### P.S:
 Try combining multiple companies into a single pull request, instead of creating separate pull for every company.

After your PR has been successfully merged with the main branch, you will be automatically added to our [Contributors](https://github.com/draco-malfoy/StartHub/blob/main/README.md#contributors-) list!!!
(if, for whatever reason you find yourself missing from the contributors list, let us know and we'll be more than happy to add you.)

**Comment by pv24** [comment]
hey i will be glad to do it

**Comment by nk183** [comment]
hi @draco-malfoy ,can I work on this please?

**Comment by PrasannaBH** [comment]
Hey i made a PR please check it 
sorry i forgot to to tell you here before making a PR
@draco-malfoy

**Comment by draco-malfoy** [comment]
> hey i will be glad to do it

Thank you. Anyone feeling to contribute can take this up.

**Comment by draco-malfoy** [comment]
> hi @draco-malfoy ,can I work on this please?

@nk183 Yes. I have requested a few changes. Kindly look into.

**Comment by draco-malfoy** [comment]
> Hey i made a PR please check it
> sorry i forgot to to tell you here before making a PR
> @draco-malfoy

@PrasannaBH Thank you for you contribution. PR merged.

**Comment by rhemzypm** [comment]
Hey i made a PR please check it
sorry i forgot to to tell you here before making a PR
I hope you accept my Pull
@draco-malfoy

**Comment by Galaxy-Coding** [comment]
may I work on this?
I’m really excited to contribute to open source for the first time! 😄

**Comment by Stefan8412** [comment]
can i try this? i would like to contribute for the first time.

**Comment by ImagineZero0** [comment]
Hey, @draco-malfoy  Can I work on this.?

**Comment by draco-malfoy** [comment]
@Galaxy-Coding @Stefan8412 @ImagineZero0 You can raise a PR. I'll merge them after reviewing. Thank you.

**Comment by ImagineZero0** [comment]
Sure @draco-malfoy, I will do so...

**Comment by aleqske** [comment]
I would like to contribute to this.

**Comment by draco-malfoy** [comment]
@alexkimeu0 Thank you for wanting to contribute. Please read the contributing guidelines before making a PR.

**Comment by KiranThomasCherian** [comment]
Could i help ?

**Comment by draco-malfoy** [comment]
@KiranThomasCherian Yes.

**Comment by ImagineZero0** [comment]
Hey @draco-malfoy, I also added my PR. Could you please review it...

**Comment by Suhas1998** [comment]
Hey @draco-malfoy ,  Can I contribute to this?

**Comment by Suhas1998** [comment]
Hi @draco-malfoy ... I added some companies to the list .. Please review my Pull request and accept it!

**Comment by yashbhal** [comment]
Hi, I added a few companies to the list in a format similar to the other contributions & modified the required files as well. 
This is my first attempt at contributing to open-source and I hope the pull request is accepted.
Thanks!

**Comment by draco-malfoy** [comment]
Thank you @Suhas1998 and @yashbhal for the contribution. The team will review 'em PR's shortly.

**Comment by senbagaraman04** [comment]
@draco-malfoy , added new company with PR #43

**Comment by draco-malfoy** [comment]
Thank you @senbagaraman04. We'll review the PR shortly.

**Comment by naisofly** [comment]
Added new company with PR #45

**Comment by KiranThomasCherian** [comment]
@draco-malfoy  Could you check my request, i had rectified all issues

**Comment by draco-malfoy** [comment]
Thank you @naisofly and @KiranThomasCherian for the contribution. The team will review the PR's by today.

**Comment by ramkrishn123** [comment]
I would like to contribute on it

**Comment by draco-malfoy** [comment]
@ramkrishn123 Thank you for contributing to contribute. Please raise a PR.

**Comment by tashfeenMustafa** [comment]
@draco-malfoy Hi, can I add to the project as per the instructions? Could you please elaborate which companies to add? Are these real life companies or made up? And if they are real life companies, is there a certain criteria for it?

**Comment by draco-malfoy** [comment]
@tashfeenMustafa Any company that you can work for to get paid will do. Please read guidelines creating PR.

**Comment by shivarajloni** [comment]
hey! can i contribute

**Comment by draco-malfoy** [comment]
@shivarajloni Yes!

**Comment by Nitish-web-nik** [comment]
I would like to contribute to this issue, can I ?

**Comment by draco-malfoy** [comment]
@Nitish-web-nik Yes!

**Comment by adarsh115** [comment]
Can I still contribute? Actually, I found this whole HackOctober thing today only. So please allow me If I am still eligible

**Comment by draco-malfoy** [comment]
@adarsh115 Yes!

**Comment by adarsh115** [comment]
hey @draco-malfoy  I have added files and made a contribution as per readme.md. Please review my pull request

**Comment by draco-malfoy** [comment]
@adarsh115 couldn't find any PR with account @adarsh115. Please raise PR again

**Comment by 123mansha** [comment]
hey @draco-malfoy added company name and details.
please review my PR #111

**Comment by 123mansha** [comment]
hey @draco-malfoy added the required according to readme.md
please review it.

**Comment by draco-malfoy** [comment]
@123mansha reviewed!

**Comment by utkarsh147-del** [comment]
Please assign this work to me

**Comment by draco-malfoy** [comment]
Hi @utkarsh147-del anyone can take this up!

**Comment by utkarsh147-del** [comment]
Thanks for your reply.

**Comment by SanthoshS20** [comment]
I have added company details and raised PR.

**Comment by hunzlahmalik** [comment]
Added Company and created PullRequest

**Comment by tanishghosh** [comment]
Hi @draco-malfoy ! Can you look into the PR raised ?

**Comment by surajkumarbera** [comment]
hey @draco-malfoy I have added files. Please review my pull request.
